import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";
import { query } from "@/lib/db";
import { JWT_SECRET } from "@/lib/jwt";
import { logActivity } from "@/lib/logger";

async function ensureKalenderTableExists() {
  try {
    await query(`
      CREATE TABLE IF NOT EXISTS kalender_akademik (
        id VARCHAR(255) PRIMARY KEY,
        tanggal DATE NOT NULL,
        jenis VARCHAR(50) NOT NULL,
        keterangan TEXT NOT NULL,
        "tahunAjaranId" VARCHAR(255)
      );
    `);
  } catch {}
}

export async function GET(request: Request) {
  try {
    await ensureKalenderTableExists();
    const { searchParams } = new URL(request.url);
    const tahunAjaranId = searchParams.get("tahunAjaranId");
    const tanggal = searchParams.get("tanggal");

    let conditions: string[] = [];
    let params: any[] = [];

    if (tahunAjaranId) {
      params.push(tahunAjaranId);
      conditions.push(`"tahunAjaranId" = $${params.length}`);
    }

    if (tanggal) {
      params.push(tanggal);
      conditions.push(`tanggal = $${params.length}`);
    }

    const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";

    const sql = `SELECT * FROM kalender_akademik ${whereClause} ORDER BY tanggal ASC`;
    const result = await query(sql, params);

    return NextResponse.json({ success: true, data: result.rows });
  } catch (error: any) {
    console.error("GET Kalender Error:", error);
    return NextResponse.json({ success: true, data: [] });
  }
}

export async function POST(request: Request) {
  try {
    await ensureKalenderTableExists();
    const cookieStore = await cookies();
    const token = cookieStore.get("accessToken")?.value;
    if (!token) {
      return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
    }

    const { payload } = await jwtVerify(token, JWT_SECRET);
    if (payload.role !== "ADMIN") {
      return NextResponse.json({ success: false, message: "Forbidden: Hanya Admin yang dapat mengelola kalender" }, { status: 403 });
    }

    const body = await request.json();
    const { tanggal, jenis, keterangan, tahunAjaranId } = body;

    if (!tanggal || !jenis || !keterangan) {
      return NextResponse.json({ success: false, message: "Tanggal, jenis, dan keterangan wajib diisi" }, { status: 400 });
    }

    const kalenderId = crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2);

    await query(
      `INSERT INTO kalender_akademik (id, tanggal, jenis, keterangan, "tahunAjaranId")
       VALUES ($1, $2, $3, $4, $5)`,
      [kalenderId, tanggal, jenis, keterangan, tahunAjaranId || null]
    );

    const adminId = payload.id as string;
    const forwarded = request.headers.get("x-forwarded-for");
    const ip = forwarded ? forwarded.split(/,\s*/)[0] : request.headers.get("x-real-ip") || "127.0.0.1";
    await logActivity(adminId, "TAMBAH_KALENDER", "Kalender", { keterangan, tanggal, jenis }, ip);

    // Auto-generate pengumuman draft for admin confirmation
    try {
      const judul = `Agenda: ${keterangan}`;
      const isi = `Agenda Kalender Akademik "${keterangan}" telah dijadwalkan pada tanggal ${tanggal} (${jenis === 'LIBUR_NASIONAL' ? 'Libur Nasional' : jenis === 'CUTI_BERSAMA' ? 'Cuti Bersama' : 'Kegiatan Sekolah'}). Silakan tinjau dan publikasikan pengumuman ini.`;

      await query(
        `INSERT INTO pengumuman (id, judul, isi, "dibuatOlehId", "targetJenjang", pinned, foto, "tahunAjaranId", "isPublished", "isAutoGenerated", "tanggalPublish", "createdAt")
         VALUES (gen_random_uuid(), $1, $2, $3, NULL, false, NULL, $4, false, true, NOW(), NOW())`,
        [judul, isi, adminId, tahunAjaranId || null]
      );
    } catch (annErr) {
      console.error("Failed to auto-generate pengumuman for kalender:", annErr);
    }

    return NextResponse.json({ success: true, message: "Kegiatan kalender berhasil ditambahkan dan draft pengumuman telah dibuat" });
  } catch (error: any) {
    console.error("POST Kalender Error:", error);
    return NextResponse.json({ success: false, message: error.message || "Server error" }, { status: 500 });
  }
}
