/* eslint-disable */
"use client";

import { useEffect, useState, useCallback, useMemo } from "react";
import { api } from "@/lib/api";
import { toast } from "sonner";
import {
  Megaphone,
  Plus,
  Trash2,
  Edit,
  Loader2,
  Pin,
  Eye,
  X,
} from "lucide-react";
import type { AxiosError } from "axios";
import Image from "next/image";
import Modal from "@/components/shared/Modal";
import ConfirmModal from "@/components/shared/ConfirmModal";

type Pengumuman = {
  id: string;
  judul: string;
  isi: string;
  targetJenjang: "MTS" | "MA" | null;
  pinned: boolean;
  foto: string | null;
  isPublished: boolean;
  isAutoGenerated: boolean;
  tanggalPublish: string;
  dibuatOleh: { nama: string; role: string };
  tahunAjaran?: { label: string; semester?: string } | null;
};

type TahunAjaran = {
  id: string;
  label: string;
  semester: string;
  isAktif: boolean;
};

export default function AdminPengumumanPage() {
  const [pengumumanList, setPengumumanList] = useState<Pengumuman[]>([]);
  const [tahunAjaranList, setTahunAjaranList] = useState<TahunAjaran[]>([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [selectedTA, setSelectedTA] = useState("");
  const [filterJenjang, setFilterJenjang] = useState("");

  // Modal Create/Edit
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState({
    judul: "",
    isi: "",
    targetJenjang: "" as "" | "MTS" | "MA",
    pinned: false,
    foto: "",
    tahunAjaranId: "",
  });
  const [uploadingPhoto, setUploadingPhoto] = useState(false);
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  // Modal Detail Image Preview
  const [previewImage, setPreviewImage] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [pRes, taRes] = await Promise.all([
        api.get<{ success: boolean; data: Pengumuman[] }>(
          `/pengumuman${selectedTA ? `?tahunAjaranId=${selectedTA}` : ""}`,
        ),
        api.get<{ success: boolean; data: TahunAjaran[] }>("/tahun-ajaran"),
        api.post("/pengumuman/mark-read").catch(() => {}),
      ]);
      const rawData = pRes.data.data as any;
      const list = Array.isArray(rawData) ? rawData : rawData?.data || [];
      setPengumumanList(list);
      setTahunAjaranList(taRes.data.data);
    } catch (err) {
      toast.error("Gagal memuat data pengumuman");
    } finally {
      setLoading(false);
    }
  }, [selectedTA]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setPhotoFile(file);
    const previewUrl = URL.createObjectURL(file);
    setForm((prev) => ({ ...prev, foto: previewUrl }));
    toast.success("Foto dipilih (preview aktif). Klik Simpan untuk mengunggah.");
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.judul || !form.isi) {
      toast.error("Judul dan isi pengumuman wajib diisi");
      return;
    }

    setIsSaving(true);
    try {
      let finalFoto = form.foto;
      if (photoFile) {
        setUploadingPhoto(true);
        const formData = new FormData();
        formData.append("file", photoFile);
        const res = await api.post<{ data: { foto: string } }>(
          "/upload",
          formData,
          {
            headers: { "Content-Type": "multipart/form-data" },
          },
        );
        finalFoto = res.data.data.foto;
        setPhotoFile(null);
        setUploadingPhoto(false);
      }

      const payload = {
        ...form,
        targetJenjang: form.targetJenjang || null,
        tahunAjaranId: form.tahunAjaranId || null,
        foto: finalFoto || null,
      };

      if (editingId) {
        await api.put(`/pengumuman/${editingId}`, payload);
        toast.success("Pengumuman berhasil diperbarui");
      } else {
        await api.post("/pengumuman", payload);
        toast.success("Pengumuman berhasil dibuat");
      }

      setIsModalOpen(false);
      setEditingId(null);
      setPhotoFile(null);
      setForm({
        judul: "",
        isi: "",
        targetJenjang: "",
        pinned: false,
        foto: "",
        tahunAjaranId: "",
      });
      fetchData();
    } catch (err: any) {
      const error = err as AxiosError<{ message: string }>;
      toast.error(
        error.response?.data?.message ?? "Gagal menyimpan pengumuman",
      );
    } finally {
      setIsSaving(false);
      setUploadingPhoto(false);
    }
  };

  const handlePublish = async (id: string) => {
    try {
      await api.put(`/pengumuman/${id}/publish`);
      toast.success("Pengumuman berhasil dipublikasikan");
      fetchData();
    } catch (err) {
      toast.error("Gagal mempublikasikan pengumuman");
    }
  };

  const handleConfirmDelete = async () => {
    if (!deleteId) return;
    setIsDeleting(true);
    try {
      await api.delete(`/pengumuman/${deleteId}`);
      toast.success("Pengumuman berhasil dihapus");
      setDeleteId(null);
      fetchData();
    } catch (err) {
      toast.error("Gagal menghapus pengumuman");
    } finally {
      setIsDeleting(false);
    }
  };

  const filteredList = useMemo(() => {
    return pengumumanList.filter((p) => {
      if (filterJenjang && p.targetJenjang && p.targetJenjang !== filterJenjang)
        return false;
      return true;
    });
  }, [pengumumanList, filterJenjang]);

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center text-white"
            style={{ backgroundColor: "var(--primary)" }}
          >
            <Megaphone size={20} />
          </div>
          <div>
            <h1 className="text-xl font-bold text-[var(--text-primary)]">
              Manajemen Pengumuman Sekolah
            </h1>
            <p className="text-[13px] text-[var(--text-secondary)] mt-0.5">
              Buat, kelola, dan publikasikan pengumuman untuk guru dan staf.
            </p>
          </div>
        </div>
        <button
          onClick={() => {
            setEditingId(null);
            setForm({
              judul: "",
              isi: "",
              targetJenjang: "",
              pinned: false,
              foto: "",
              tahunAjaranId: "",
            });
            setIsModalOpen(true);
          }}
          className="w-full sm:w-auto px-4 py-2.5 text-white text-[13px] font-bold rounded-xl shadow-sm flex items-center justify-center gap-2 transition-all cursor-pointer"
          style={{ backgroundColor: "var(--primary)" }}
        >
          <Plus size={16} /> Buat Pengumuman
        </button>
      </div>

      {/* Filter Bar (w-full on mobile, side-by-side on sm+) */}
      <div className="bg-[var(--surface)] border justify-end border-[var(--border)] p-4 rounded-2xl flex items-center gap-3 shadow-sm">
        <select
          value={selectedTA}
          onChange={(e) => setSelectedTA(e.target.value)}
          className="w-full sm:w-auto px-3.5 py-2 bg-[var(--surface-subtle)] border border-[var(--border)] rounded-xl text-[13px] font-bold text-[var(--text-primary)] focus:outline-none cursor-pointer"
        >
          <option value="">Semua Tahun Ajaran</option>
          {tahunAjaranList.map((ta) => (
            <option key={ta.id} value={ta.id}>
              TA {ta.label} - Smt {ta.semester}
            </option>
          ))}
        </select>
        <select
          value={filterJenjang}
          onChange={(e) => setFilterJenjang(e.target.value)}
          className="w-full sm:w-auto px-3.5 py-2 bg-[var(--surface-subtle)] border border-[var(--border)] rounded-xl text-[13px] font-bold text-[var(--text-primary)] focus:outline-none cursor-pointer"
        >
          <option value="">Semua Jenjang</option>
          <option value="MTS">MTS</option>
          <option value="MA">MA</option>
        </select>
      </div>

      {/* Main List */}
      {loading ? (
        <div className="flex justify-center py-20">
          <Loader2
            size={36}
            className="animate-spin"
            style={{ color: "var(--primary)" }}
          />
        </div>
      ) : filteredList.length === 0 ? (
        <div className="bg-[var(--surface)] border border-[var(--border)] rounded-2xl p-16 text-center shadow-sm">
          <Megaphone
            size={36}
            className="text-[var(--text-tertiary)] mx-auto mb-3 opacity-40"
          />
          <p className="font-bold text-[var(--text-primary)]">
            Belum ada pengumuman
          </p>
          <p className="text-[13px] text-[var(--text-secondary)] mt-1">
            Buat pengumuman pertama Anda atau periksa draft kalender akademik.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {filteredList.map((item) => (
            <div
              key={item.id}
              className={`bg-[var(--surface)] border rounded-2xl p-6 shadow-sm flex flex-col justify-between transition-all ${
                item.pinned
                  ? "border-[var(--primary)]/50 ring-1 ring-[var(--primary)]/20"
                  : "border-[var(--border)]"
              }`}
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    {item.pinned && (
                      <span
                        className="px-2 py-0.5 text-[10px] font-black rounded flex items-center gap-1"
                        style={{
                          backgroundColor: "var(--primary-subtle)",
                          color: "var(--primary)",
                        }}
                      >
                        <Pin size={10} /> PINNED
                      </span>
                    )}
                    {item.targetJenjang && (
                      <span className="px-2 py-0.5 bg-blue-500/10 text-blue-600 dark:text-blue-400 text-[10px] font-black rounded">
                        {item.targetJenjang}
                      </span>
                    )}
                    {!item.isPublished && (
                      <span className="px-2 py-0.5 bg-amber-500/10 text-amber-600 text-[10px] font-black rounded animate-pulse">
                        DRAFT
                      </span>
                    )}
                  </div>
                  <span className="text-[11px] text-[var(--text-tertiary)]">
                    {new Date(item.tanggalPublish).toLocaleDateString("id-ID", {
                      day: "numeric",
                      month: "short",
                      year: "numeric",
                    })}
                  </span>
                </div>

                <h3 className="text-base font-bold text-[var(--text-primary)]">
                  {item.judul}
                </h3>
                <p className="text-[13px] text-[var(--text-secondary)] line-clamp-3 whitespace-pre-wrap">
                  {item.isi}
                </p>

                {item.foto && (
                  <div
                    onClick={() => setPreviewImage(item.foto)}
                    className="relative w-full h-40 rounded-xl overflow-hidden border border-[var(--border)] cursor-pointer group mt-2"
                  >
                    <Image
                      src={item.foto}
                      alt="Lampiran"
                      fill
                      className="object-cover group-hover:scale-105 transition-transform"
                      unoptimized
                    />
                    <div className="absolute inset-0 bg-black/30 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center text-white text-[12px] font-bold gap-1.5">
                      <Eye size={16} /> Lihat Gambar
                    </div>
                  </div>
                )}
              </div>

              <div className="pt-4 mt-4 border-t border-[var(--border-subtle)] flex items-center justify-between">
                <span className="text-[11px] text-[var(--text-tertiary)] truncate">
                  Oleh: {item.dibuatOleh.nama}
                </span>
                <div className="flex items-center gap-2">
                  {!item.isPublished && (
                    <button
                      onClick={() => handlePublish(item.id)}
                      className="px-3 py-1.5 text-white text-[11px] font-bold rounded-lg shadow-sm transition-colors cursor-pointer"
                      style={{ backgroundColor: "var(--primary)" }}
                    >
                      PUBLISH
                    </button>
                  )}
                  <button
                    onClick={() => {
                      setEditingId(item.id);
                      setForm({
                        judul: item.judul,
                        isi: item.isi,
                        targetJenjang: item.targetJenjang || "",
                        pinned: item.pinned,
                        foto: item.foto || "",
                        tahunAjaranId: "",
                      });
                      setIsModalOpen(true);
                    }}
                    className="p-2 hover:bg-[var(--surface-subtle)] rounded-lg text-[var(--text-secondary)] transition-colors cursor-pointer"
                    title="Edit"
                  >
                    <Edit size={16} />
                  </button>
                  <button
                    onClick={() => setDeleteId(item.id)}
                    className="p-2 hover:bg-rose-500/10 rounded-lg text-rose-500 transition-colors cursor-pointer"
                    title="Hapus"
                  >
                    <Trash2 size={16} />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ─── Modal Create/Edit ─── */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingId ? "Edit Pengumuman" : "Buat Pengumuman Baru"}
        description="Publikasikan pengumuman untuk guru dan staf"
        maxWidth="xl"
      >
        <form onSubmit={handleSave} className="space-y-4">
          <div>
            <label className="block text-[11px] font-bold uppercase tracking-wider text-[var(--text-secondary)] mb-1">
              Judul Pengumuman *
            </label>
            <input
              type="text"
              value={form.judul}
              onChange={(e) => setForm({ ...form, judul: e.target.value })}
              placeholder="Contoh: Rapat Koordinasi Bulanan..."
              className="w-full px-3.5 py-2.5 bg-[var(--surface)] border border-[var(--border)] rounded-xl text-[13px] text-[var(--text-primary)] focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-[11px] font-bold uppercase tracking-wider text-[var(--text-secondary)] mb-1">
              Isi Pengumuman *
            </label>
            <textarea
              rows={5}
              value={form.isi}
              onChange={(e) => setForm({ ...form, isi: e.target.value })}
              placeholder="Tuliskan isi pengumuman secara lengkap..."
              className="w-full px-3.5 py-2.5 bg-[var(--surface)] border border-[var(--border)] rounded-xl text-[13px] text-[var(--text-primary)] focus:outline-none resize-none"
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-[11px] font-bold uppercase tracking-wider text-[var(--text-secondary)] mb-1">
                Target Jenjang
              </label>
              <select
                value={form.targetJenjang}
                onChange={(e) =>
                  setForm({ ...form, targetJenjang: e.target.value as any })
                }
                className="w-full px-3.5 py-2.5 bg-[var(--surface)] border border-[var(--border)] rounded-xl text-[13px] text-[var(--text-primary)] focus:outline-none cursor-pointer"
              >
                <option value="">Semua Jenjang</option>
                <option value="MTS">MTS</option>
                <option value="MA">MA</option>
              </select>
            </div>
            <div>
              <label className="block text-[11px] font-bold uppercase tracking-wider text-[var(--text-secondary)] mb-1">
                Tahun Ajaran & Semester
              </label>
              <select
                value={form.tahunAjaranId}
                onChange={(e) =>
                  setForm({ ...form, tahunAjaranId: e.target.value })
                }
                className="w-full px-3.5 py-2.5 bg-[var(--surface)] border border-[var(--border)] rounded-xl text-[13px] text-[var(--text-primary)] focus:outline-none cursor-pointer"
              >
                <option value="">Umum (Tanpa Filter TA)</option>
                {tahunAjaranList.map((ta) => (
                  <option key={ta.id} value={ta.id}>
                    TA {ta.label} - Smt {ta.semester}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div>
            <label className="block text-[11px] font-bold uppercase tracking-wider text-[var(--text-secondary)] mb-1">
              Lampiran Gambar (Opsional)
            </label>
            <div className="flex items-center gap-3">
              <input
                type="file"
                accept="image/*"
                onChange={handlePhotoUpload}
                className="text-[12px] text-[var(--text-secondary)] file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-[12px] file:font-bold file:bg-[var(--primary)]/10 file:text-[var(--primary)] hover:file:bg-[var(--primary)]/20 cursor-pointer"
              />
              {uploadingPhoto && (
                <Loader2
                  size={18}
                  className="animate-spin"
                  style={{ color: "var(--primary)" }}
                />
              )}
            </div>
            {form.foto && (
              <div className="mt-3 relative w-32 h-20 rounded-lg overflow-hidden border border-[var(--border)]">
                <Image
                  src={form.foto}
                  alt="Preview"
                  fill
                  className="object-cover"
                  unoptimized
                />
              </div>
            )}
          </div>
          <div className="flex items-center gap-3 pt-2">
            <input
              type="checkbox"
              id="pinned"
              checked={form.pinned}
              onChange={(e) => setForm({ ...form, pinned: e.target.checked })}
              className="w-4 h-4 accent-[var(--primary)] cursor-pointer"
            />
            <label
              htmlFor="pinned"
              className="text-[13px] font-bold text-[var(--text-primary)] cursor-pointer select-none"
            >
              Sematkan di Atas (Pinned)
            </label>
          </div>

          <div className="pt-4 border-t border-[var(--border)] flex items-center justify-end gap-3">
            <button
              type="button"
              onClick={() => {
                setIsModalOpen(false);
                setPhotoFile(null);
              }}
              className="px-4 py-2 text-[13px] font-bold text-[var(--text-secondary)] border border-[var(--border)] rounded-xl cursor-pointer"
            >
              Batal
            </button>
            <button
              type="submit"
              disabled={isSaving}
              className="px-5 py-2 text-white text-[13px] font-bold rounded-xl flex items-center gap-2 shadow-sm cursor-pointer"
              style={{ backgroundColor: "var(--primary)" }}
            >
              {isSaving && <Loader2 size={14} className="animate-spin" />}{" "}
              Simpan Pengumuman
            </button>
          </div>
        </form>
      </Modal>

      {/* ─── Image Preview Lightbox Modal ─── */}
      {previewImage && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm"
          onClick={() => setPreviewImage(null)}
        >
          <div className="relative max-w-4xl max-h-[90vh] overflow-hidden rounded-2xl">
            <button
              onClick={() => setPreviewImage(null)}
              className="absolute top-4 right-4 z-10 p-2 bg-black/60 text-white rounded-full hover:bg-black cursor-pointer"
            >
              <X size={20} />
            </button>
            <Image
              src={previewImage}
              alt="Preview"
              width={1000}
              height={800}
              className="object-contain max-h-[90vh] w-auto h-auto rounded-2xl"
              unoptimized
            />
          </div>
        </div>
      )}

      {/* ─── Confirm Delete Modal ─── */}
      <ConfirmModal
        isOpen={Boolean(deleteId)}
        onClose={() => setDeleteId(null)}
        onConfirm={handleConfirmDelete}
        title="Hapus Pengumuman"
        message="Apakah Anda yakin ingin menghapus pengumuman ini? Tindakan ini tidak dapat dibatalkan."
        confirmText="Hapus"
        isDeleting={isDeleting}
        variant="danger"
      />
    </div>
  );
}
