/* eslint-disable */
import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";
import { query } from "@/lib/db";
import { JWT_SECRET } from "@/lib/jwt";
import { pengumumanCreateSchema } from "@/lib/validations";
import { logActivity } from "@/lib/logger";

async function ensurePengumumanTablesExist() {
  try {
    await query(`
      CREATE TABLE IF NOT EXISTS pengumuman (
        id VARCHAR(255) PRIMARY KEY,
        judul TEXT NOT NULL,
        isi TEXT NOT NULL,
        "dibuatOlehId" VARCHAR(255) NOT NULL,
        "targetJenjang" VARCHAR(50),
        pinned BOOLEAN DEFAULT false,
        foto TEXT,
        "tahunAjaranId" VARCHAR(255),
        "isPublished" BOOLEAN DEFAULT true,
        "isAutoGenerated" BOOLEAN DEFAULT false,
        "tanggalPublish" TIMESTAMP DEFAULT NOW(),
        "createdAt" TIMESTAMP DEFAULT NOW()
      );
    `);
    await query(`
      CREATE TABLE IF NOT EXISTS pengumuman_dibaca (
        id VARCHAR(255) PRIMARY KEY,
        "pengumumanId" VARCHAR(255) REFERENCES pengumuman(id) ON DELETE CASCADE,
        "userId" VARCHAR(255) NOT NULL,
        "readAt" TIMESTAMP DEFAULT NOW(),
        CONSTRAINT pengumuman_dibaca_unique_key UNIQUE ("pengumumanId", "userId")
      );
    `);
  } catch {}
}

export async function GET(request: Request) {
  try {
    await ensurePengumumanTablesExist();
    const { searchParams } = new URL(request.url);
    const isPublishedParam = searchParams.get("isPublished");
    const tahunAjaranId = searchParams.get("tahunAjaranId");

    const conditions: string[] = [];
    const params: any[] = [];

    if (isPublishedParam !== null && isPublishedParam !== undefined) {
      params.push(isPublishedParam === "true");
      conditions.push(`p."isPublished" = $${params.length}`);
    }

    if (tahunAjaranId) {
      params.push(tahunAjaranId);
      conditions.push(`p."tahunAjaranId" = $${params.length}`);
    }

    const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";

    const sql = `
      SELECT p.*,
             json_build_object('nama', u.nama, 'role', u.role) as "dibuatOleh",
             CASE WHEN ta.id IS NOT NULL THEN json_build_object('label', ta.label) ELSE NULL END as "tahunAjaran"
      FROM pengumuman p
      LEFT JOIN users u ON p."dibuatOlehId" = u.id
      LEFT JOIN tahun_ajaran ta ON p."tahunAjaranId" = ta.id
      ${whereClause}
      ORDER BY p.pinned DESC, p."tanggalPublish" DESC, p."createdAt" DESC
    `;

    const result = await query(sql, params);
    return NextResponse.json({ success: true, data: result.rows });
  } catch (error: any) {
    console.error("GET Pengumuman Error:", error);
    return NextResponse.json({ success: true, data: [] });
  }
}

export async function POST(request: Request) {
  try {
    await ensurePengumumanTablesExist();
    const cookieStore = await cookies();
    const token = cookieStore.get("accessToken")?.value;
    if (!token) {
      return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
    }

    const { payload } = await jwtVerify(token, JWT_SECRET);
    if (payload.role !== "ADMIN") {
      return NextResponse.json({ success: false, message: "Forbidden: Hanya Admin yang dapat membuat pengumuman" }, { status: 403 });
    }

    const body = await request.json();
    const parsed = pengumumanCreateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ success: false, message: parsed.error.issues[0]?.message || "Validasi gagal" }, { status: 400 });
    }

    const { judul, isi, targetJenjang, pinned, foto, tahunAjaranId, isPublished } = parsed.data;
    const published = isPublished !== undefined ? isPublished : true;
    const userId = payload.id as string;

    await query(
      `INSERT INTO pengumuman (id, judul, isi, "dibuatOlehId", "targetJenjang", pinned, foto, "tahunAjaranId", "isPublished", "tanggalPublish", "createdAt")
       VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())`,
      [
        judul,
        isi,
        userId,
        targetJenjang || null,
        pinned ? true : false,
        foto || null,
        tahunAjaranId || null,
        published,
      ]
    );

    const forwarded = request.headers.get("x-forwarded-for");
    const ip = forwarded ? forwarded.split(/,\s*/)[0] : request.headers.get("x-real-ip") || "127.0.0.1";
    await logActivity(userId, "BUAT_PENGUMUMAN", "Pengumuman", { judul }, ip);

    return NextResponse.json({ success: true, message: "Pengumuman berhasil dibuat" });
  } catch (error: any) {
    console.error("POST Pengumuman Error:", error);
    return NextResponse.json({ success: false, message: error.message || "Server error" }, { status: 500 });
  }
}
